### ISSUE TITLE
(Future Compatibility Issue): Figure handles are no longer numbers as of Matlab 2014b 

### ISSUE THREAD

**Issue by dbirman** [justingardner/mrTools#20] opened 2015-02-26 19:26 UTC
A number of functions related to figure control fail, some examples here:

When opening an individual voxel timecourse:
```
Undefined function 'real' for input arguments of type 'matlab.ui.Figure'.

Error in int2str (line 12)
x = real(x);

Error in newGraphWin (line 18)
figloc = mrGetFigLoc(['graphFigure' int2str(h)]);
```

When closing a window:
```
Undefined function 'real' for input arguments of type 'matlab.ui.Figure'.

Error in int2str (line 12)
x = real(x);

Error in closeGraphWin (line 19)
    mrSetFigLoc(['graphFigure' int2str(h)],get(h,'Position'));
```

It seems to be caused by Matlab no longer referring to figure handles as integers, instead it's necessary to call figurehandle.number.

**Comment by schluppeck** [comment] 2015-02-27 11:21
Dear all,

I have come across those… but haven’t had a chance to fork/make a pull request. In R2014b, figure handles are not ints/doubles any more

http://uk.mathworks.com/help/matlab/graphics_transition/graphics-handles-are-now-objects-not-doubles.html

and the other thing that throws mrTools code (related to some interrogator stuff, iirc) in a couple of places is that the “convenience” version of referring to properties with the dot notation is still allowed, but now case-sensitive:

http://blogs.mathworks.com/loren/2014/10/14/matlab-r2014b-graphics-part-2-using-graphics-objects/#fd562af3-d1e3-4c7c-8c35-4f46229fd693

justin: if you guys are doing everything over github now, i’ll go through there if that’s helpful.

best from nottingham
d

..
Denis Schluppeck
denis.schluppeck@nottingham.ac.uk<mailto:denis.schluppeck@nottingham.ac.uk>



On 26 Feb 2015, at 19:26, dbirman <notifications@github.com<mailto:notifications@github.com>> wrote:


A number of functions related to figure control fail, some examples here:

When opening an individual voxel timecourse:

Undefined function 'real' for input arguments of type 'matlab.ui.Figure'.

Error in int2str (line 12)
x = real(x);

Error in newGraphWin (line 18)
figloc = mrGetFigLoc(['graphFigure' int2str(h)]);


When closing a window:

Undefined function 'real' for input arguments of type 'matlab.ui.Figure'.

Error in int2str (line 12)
x = real(x);

Error in closeGraphWin (line 19)
    mrSetFigLoc(['graphFigure' int2str(h)],get(h,'Position'));


It seems to be caused by Matlab no longer referring to figure handles as integers, instead it's necessary to call figurehandle.number.

—
Reply to this email directly or view it on GitHub<https://github.com/justingardner/mrTools/issues/20>.





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by justingardner** [comment] 2015-02-27 17:05
Hey Denis,

If you have a fix for this (<cough> idiotic change by Mathworks <cough>), would be great if you could do a pull request and merge into this rep. I am still running R2013b and don't have a way to test any fixes as of this moment...

**Comment by francopestilli** [comment] 2015-02-27 17:13
This is so idiot. So one fix could be the following to address the handle as "h.Number":
>> h
h = 
  Figure (1) with properties:
      Number: 1
        Name: ''
       Color: [0.9400 0.9400 0.9400]
    Position: [440 378 560 420]
       Units: 'pixels'

>> h.Number
ans = 1

**Comment by justingardner** [comment] 2015-02-27 17:22
Yes, but the fix needs to make sure that it won't break older versions that don't have the Number property. I think in places like newGraphWin and closeGraphWin we need to do something like:

if isnumeric(h)
  fignum = h;
else
  fignum = h.Number;
end

Then use fignum instead of whenever we were expecting to get a number. Not sure if there is a way to check whether the Number field exists or not - to make extra sure. Like can you do:

isfield(h,'Number')

**Comment by francopestilli** [comment] 2015-02-27 17:24
How about get?

if isnumeric(h)
  fignum = h;
else
  fignum = get(h,'Number');
end

**Comment by justingardner** [comment] 2015-02-27 17:25
Does that work? On my version of Matlab that gives me the string 'on':

>> fig = figure;
>> get(fig,'Number')

ans =
on

**Comment by justingardner** [comment] 2015-02-27 17:26
Does isprop work?

isprop(h,'Numeric')

**Comment by justingardner** [comment] 2015-02-27 17:28
I mean,

isprop(h,'Number')...

**Comment by francopestilli** [comment] 2015-02-27 17:29
>> h = figure(1)

h = 

  Figure (1) with properties:

      Number: 1
        Name: ''
       Color: [0.9400 0.9400 0.9400]
    Position: [440 378 560 420]
       Units: 'pixels'

  Show all properties

>>  isprop(h,'Number')

ans =

     1

**Comment by justingardner** [comment] 2015-02-27 17:44
Ok. I've pushed a fix for this (both to the life branch and master) - can someone check on 2014b to make sure that the newGraphWin and closeGraphWin functions work now? They should be called when you use an interrogator for instance...

**Comment by francopestilli** [comment] 2015-03-01 16:47
I am not in the position to test currently. Maybe @schluppeck ?

**Comment by schluppeck** [comment] 2015-03-01 21:22
This works here. Tested by 

* launching using 'timecoursePlot' interrogator under R2014b (with retinotopyTutorial dataset). 
* calling `newGraphWin` and `closeGraphWin` in command line

There are a couple of headaches ahead, though. Will raise under separate ticket.

**Closed** 2015-03-02 00:09 UTC
