### ISSUE TITLE
Convert Cortical Depth Deletes ROIs

### ISSUE THREAD

**Issue by dbirman** [justingardner/mrTools#29] opened 2015-09-02 18:29 UTC
Error can be consistently re-created in s031020150815 in mlrAnatDB. Generate rV1 and rV2v ROIs on s0310_right_occipital_r90 flat, select a different base anatomy (e.g. (s0310_left_occipital_r90), convert cortical depth, crashes with error:
```
Improper assignment with rectangular empty matrix.

Error in convertROICorticalDepth (line 133)
        [roiBaseCoords(1,:) roiBaseCoords(2,:) roiBaseCoords(3,:)] =
        ind2sub(baseDims,roiBaseCoordsLinear);
```
And the ROI will be gone.

I can re-create the error consistently by being on any base other than the base that the ROIs I am trying to convert are on. (e.g. if my ROI is on left_occipital and I am on base right_occipital, it will delete my ROI when I convert any ROIs drawn on the left base).

(This error was previously reported by Joujou, but I don't think he knew why it was occurring, so it occurs on at least two machines).

**Comment by justingardner** [comment] 2015-09-05 05:17
Ok. Should be fixed. The issue is that to convert cortical depth you need to base this on a surface which has coordinates of the inner (white matter) and outer (gray matter) surfaces. Typically this is the flat map from which the ROI was drawn. ROIs used to not know who they were drawn on, so the code just defaulted to using the base anatomy that was currently being displayed. So if you were a right ROI and the current base was the left side, then it would lose all the coordinates since none of your coordinates lived on that base. Now it tries to do the analysis on the same base that the roi was created on - but will default to current if you do not have that base loaded. If it can't find more than 10% of the roi coordinates on the base, it will warn you and give up. Please check that this is all working as expected (i.e. it projects through depth as expected and does this regardless of what base is currently being displayed).

**Closed by justingardner** 2015-09-05 05:17 UTC
